apiVersion: v1
kind: Service
metadata:
  name: checkout-vpw
  labels:
    app.kubernetes.io/name: checkout-vpw
    app.kubernetes.io/instance: checkout-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-vpw
      protocol: TCP
      name: http-vpw
  selector:
    app.kubernetes.io/name: checkout-vpw
    app.kubernetes.io/instance: checkout-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
