apiVersion: v1
kind: Service
metadata:
  name: catalog-mysql-vpw
  labels:
    app.kubernetes.io/name: catalog-vpw
    app.kubernetes.io/instance: catalog-vpw
    app.kubernetes.io/component: mysql-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
spec:
  clusterIP: None   # Headless service
  ports:
    - port: 3306
      targetPort: mysql-vpw
      name: mysql-vpw
  selector:
    app.kubernetes.io/name: catalog-vpw
    app.kubernetes.io/instance: catalog-vpw
    app.kubernetes.io/component: mysql-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw