apiVersion: v1
kind: Service
metadata:
  name: catalog-service-vpw
  labels:
    app.kubernetes.io/name: catalog-vpw
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-vpw
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
