# Source: retail-store-sample-cart-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts-vpw
  labels:
    helm.sh/chart: carts-1.2.4
    app.kubernetes.io/name: carts-vpw
    app.kubernetes.io/instance: carts-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
    app.kubernetes.io/managed-by: Helm