apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-vpw
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: orders-postgres-db-vpw.c42nr5ktk6ag.ap-south-1.rds.amazonaws.com:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: ordersdbvpw
  RETAIL_ORDERS_MESSAGING_PROVIDER: sqs
  RETAIL_ORDERS_MESSAGING_SQS_TOPIC: vpw-dev-orders-queue
  #RETAIL_ORDERS_MESSAGING_SQS_TOPIC: https://sqs.ap-south-1.amazonaws.com/454143665149/vpw-dev-orders-queue
