# Source: retail-store-sample-ui-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-vpw
  labels:
    helm.sh/chart: ui-1.2.4
    app.kubernetes.io/name: ui-vpw
    app.kubernetes.io/instance: ui-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
    app.kubernetes.io/managed-by: Helm
