# Source: retail-store-sample-ui-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-vpw
data:
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog-vpw
  RETAIL_UI_ENDPOINTS_CARTS: http://carts-vpw
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout-vpw
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders-vpw