# Source: retail-store-sample-ui-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-vpw
  labels:
    helm.sh/chart: ui-1.2.4
    app.kubernetes.io/name: ui-vpw
    app.kubernetes.io/instance: ui-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP  
  ports:
    - port: 80
      targetPort: http-vpw
      protocol: TCP
      name: http-vpw
  selector:
    app.kubernetes.io/name: ui-vpw
    app.kubernetes.io/instance: ui-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw