# Source: retail-store-sample-orders-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-vpw
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: orders-rabbitmq-vpw:5672
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: orders-postgresql-vpw:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: orders-vpw