apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . }}
  labels: {{- include "catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-vpw
      protocol: TCP
      name: http-vpw
  selector: {{- include "catalog.selectorLabels" . | nindent 4 }}
