# Source: retail-store-sample-checkout-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout-sa-vpw
  labels:
    helm.sh/chart: checkout-1.2.4
    app.kubernetes.io/name: checkout-vpw
    app.kubernetes.io/instance: checkout-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
    app.kubernetes.io/managed-by: Helm