apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-vpw
  namespace: default
spec:
  serviceAccountName: aws-cli-sa-vpw
  containers:
  - name: aws-cli-vpw
    image: amazon/aws-cli
    command: ["sleep", "infinity"]