# Catalog Custom Values
mysql:
  create: true 

app:
  persistence:
    provider: mysql
    endpoint: ""
    database: "catalog-vpw"

    secret:
      create: true
      name: catalog-db-vpw
      username: vpwadmin
      password: vpwdatabase101