# Source: retail-store-sample-orders-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa-vpw
  labels:
    helm.sh/chart: orders-1.2.4
    app.kubernetes.io/name: orders-vpw
    app.kubernetes.io/instance: orders-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
    app.kubernetes.io/managed-by: Helm