apiVersion: v1
kind: Service
metadata:
  name: catalog-service-vpw
  labels:
    app.kubernetes.io/name: catalog-vpw
    app.kubernetes.io/instance: catalog-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-vpw
    app.kubernetes.io/instance: catalog-vpw
    app.kubernetes.io/component: service-vpw
    app.kubernetes.io/owner: retail-store-sample-vpw
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
